version: "3.8"
services:
  superagent:
    build:
      context: ./external/superagent/libs/superagent
    container_name: gaigentic-superagent
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/superagent
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=debug
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
     
    depends_on:
      - db
      - redis
  backend:
    build: ./backend
    env_file:
      - .env.development
    ports:
      - "8001:8001"
    depends_on:
      - superagent
      - db
      - redis
  frontend:
    build:
      context: ./frontend
    container_name: gaigentic-frontend
    command: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
