version: "3.8"
services:
  superagent:
    image: homanp/superagent:latest
    ports:
      - "8080:8080"
  gaigentic-backend:
    build: ./backend
    env_file:
      - .env.development
    ports:
      - "8001:8001"
    depends_on:
      - superagent
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
