version: "3.8"
services:
  superagent:
    build:
      context: ./superagent/libs/superagent
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    env_file:
      - .env.development
    ports:
      - "8001:8001"
    depends_on:
      - superagent
      - db
      - redis
  frontend:
    build:
      context: ./frontend
    container_name: gaigentic-frontend
    command: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
