version: "3.8"
services:
  backend:
    build: ./backend
    env_file: .env.production
    restart: always
    volumes:
      - /data/logs:/app/logs
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superagent
    volumes:
      - /data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - /data/redis:/data
volumes:
  data:
