#
# Auto generated by Alembic - please adjust! #
#

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision = "547a6a017bd2"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
